name: Deploy Lambda to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download precompiled psycopg2 for AWS Lambda
        run: |
          curl -L -o psycopg2.zip https://github.com/jkehler/awslambda-psycopg2/releases/download/v2.9.5/psycopg2-binary-layer.zip
          unzip psycopg2.zip -d psycopg2_package

      - name: Package Lambda code
        run: |
          mkdir package
          cp lambda_handler.py package/
          cp -r psycopg2_package/python/* package/
          cd package && zip -r ../lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy code to Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://lambda.zip

      - name: Esperar a que se complete la actualización
        run: sleep 20

      - name: Update Lambda environment variables
        run: |
          aws lambda update-function-configuration \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --environment "Variables={
              DB_HOST='${{ secrets.DB_HOST }}',
              DB_PORT='${{ secrets.DB_PORT }}',
              DB_NAME='${{ secrets.DB_NAME }}',
              DB_USER='${{ secrets.DB_USER }}',
              DB_PASSWORD='${{ secrets.DB_PASSWORD }}'
            }"
