name: Deploy Lambda with psycopg2 Layer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package Lambda handler
        run: |
          zip lambda.zip lambda_handler.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Lambda code
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://lambda.zip

      - name: Update environment variables
        run: |
          aws lambda update-function-configuration \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            ----layers arn:aws:lambda:us-east-1:877085696533:layer:psycopg2-aws-lambda:2 \
            --environment "Variables={
              DB_HOST='${{ secrets.DB_HOST }}',
              DB_PORT='${{ secrets.DB_PORT }}',
              DB_NAME='${{ secrets.DB_NAME }}',
              DB_USER='${{ secrets.DB_USER }}',
              DB_PASSWORD='${{ secrets.DB_PASSWORD }}'
            }"
