name: Build and Deploy Lambda with psycopg2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Lambda package in Lambda-compatible container
        run: |
          docker run --rm -v "$PWD":/var/task public.ecr.aws/lambda/python:3.10-build bash -c "
            yum install -y gcc postgresql-devel python3-devel zip &&
            pip3 install psycopg2-binary -t ./python &&
            cp lambda_handler.py ./python &&
            cd python && zip -r9 /var/task/lambda.zip . &&
            echo '✅ lambda.zip creado correctamente en entorno Lambda real'
          "
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy code to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://lambda.zip

      - name: Wait for deployment to complete
        run: sleep 20

      - name: Update Lambda environment variables
        run: |
          aws lambda update-function-configuration \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --environment "Variables={
              DB_HOST='${{ secrets.DB_HOST }}',
              DB_PORT='${{ secrets.DB_PORT }}',
              DB_NAME='${{ secrets.DB_NAME }}',
              DB_USER='${{ secrets.DB_USER }}',
              DB_PASSWORD='${{ secrets.DB_PASSWORD }}'
            }"
